[build]
  base = "/"
  command = "cd src && npm run build"
  publish = "src/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_PRIVATE_STANDALONE = "true"